config/routes.rb
SharingIsLoving::Application.routes.draw do
  devise_for :users

  resources :items do
    member do
      get 'like'
    end
    resources :versions do
      member do
        get 'rollback'
      end
    end
  end
  resources :uploads
  resources :tags, :only => :show
  resources :comments, :only => :create
  resource :search

  root :to => 'items#index'

end

app/controllers/versions_controller.rb
class VersionsController < RestrictedAccessController
  
  def show
    @item = Item.find(params[:item_id])
    @version = @item.versions.where(:version => params[:id]).first
  end
  
  def rollback
    @item = Item.find(params[:item_id])
    @item.rollback!(params[:id])
    redirect_to @item
  end
  
end

app/views/versions/show.html.haml
.row-fluid
	.span8.content
		%table.table.files
			%tbody
				%tr
					%td.preview
						%img.img-polaroid(src="#{@version.preview.thumb.url}" style="margin:0 10px 0 0;width:100px;height:100px")
						%ul
							- unless @version.file.file.nil?
								%li
									Size:
									= number_to_human_size(@version.file.file.size)
								%li
									Added:
									= @version.created_at.strftime("%m/%d/%Y")
							- unless @version.user.blank?
								%li 
									By:
									= @version.user.name
							%li
								Likes
								%span{:id => "like_count_#{@version._id}"}
									(#{@version.rating_count})
								= link_to_function('Like...', "sendLike('#{@version._id}')")
					%td
						%h4
							= @version.name
							%a.edit-item.icon-pencil{:href=> edit_item_path(@version)}
						.download
							%span.icon-file
							%a(href="#{@version.file.url}")
								= @version.file_filename
						%p= @version.description
						- unless @version.tags.blank?
							%p.tags 
								Tags:
								= @version.tags.map{|t| link_to(t, tag_path(t)) }.join(', ').html_safe
						%p
							%a.btn{ :href => item_path(@item) } Close version
							%a.btn.btn-primary{ :href => rollback_item_version_path(@item, params[:id]) } Rollback to this version