config/routes.rb
SharingIsLoving::Application.routes.draw do
  devise_for :users

  resources :items do
    member do
      get 'like'
    end
    resources :versions do
      member do
        get 'rollback'
      end
    end
  end
  resources :uploads
  resources :tags, :only => :show
  resources :comments, :only => :create
  resource :search

  root :to => 'items#index'

end

app/models/item.rb
class Item
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Document::Taggable
  include Mongoid::Search
  include Mongoid::Versioning
    
  mount_uploader :file, FileUploader do
    def store_dir
      model.path
    end
  end
  
  mount_uploader :preview, PreviewUploader do
    def store_dir
      model.path('previews')
    end
  end
  
  search_in :name, :description, :taggings => :name
  
  after_initialize :create_token
  
  embeds_many :ratings
  embeds_many :comments
  
  has_many :activities, autosave: true 
  def activity_by person, activity='updated'
    activities.build(:user => person, :type => activity.to_s)
  end
  
  belongs_to :user
  def created_by
    user
  end
  def created_by= person
    user= person
  end

  field :name
  field :description
  field :secure_token
  field :rating_count, :type => Integer, :default => 0
  
  default_scope desc(:rating_count).desc(:created_at)
  
  accepts_nested_attributes_for :ratings
  
  def path base='files'
    File.join(Rails.env, 'items', base, self.secure_token)
  end
      
  def create_token
    self.secure_token = self.secure_token || SecureRandom.uuid
  end
  
  def rollback! index
    self.versionless do
      self.revise!
      self.versions.where(:version => index).first.attributes.each do |key,value|
        self.write_attribute(key,value) unless key=='_id' || key=='version'
      end
      self.created_at = Time.now
      self.save
    end
  end
  
  class Tag
    attr_reader :name
    def initialize name=""
      @name = name
    end
  end
  
  def taggings
    self.tags.map{|n| Tag.new(n)}
  end
  
  def like user_id
    self.ratings.build(:value => 1, :user_id => user_id)
    self.rating_count = self.rating_count + 1
  end
  
  include Rails.application.routes.url_helpers

  def to_jq_upload
    {
      "name" => self.name,
      "filename" => self.file_filename,
      "description" => self.description,
      "tags" => self.tags,
      "tags_url" => tag_path(''),
      "size" => self.file.size,
      "url" => self.file.url,
      "delete_url" => item_path(self),
      "delete_type" => "DELETE" 
    }
  end

  
  
end

app/controllers/items_controller.rb
class ItemsController < RestrictedAccessController
  before_filter :load_tags, :load_stream
  
  def index
    respond_to do |format|
      @items = Item.page(params[:page])
      format.html do
        if request.xhr?
          render :partial => '/items/items_list.html.haml', :layout => false
        end
      end
    end
  end
  
  def new
    @item = Item.new
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    respond_to do |format|
      @item = Item.find(params[:id])
      @item.activity_by(current_user, :updated)
      @item.update_attributes(params[:item])
      format.html do
        redirect_to item_path(@item)
      end
    end
  end
  
  def like
    respond_to do |format|
      @item = Item.find(params[:id])
      @item.like(current_user._id)
      @item.versionless do |item|
        item.update_attributes(params[:item])
      end
      format.html do
        render :text => @item.rating_count
      end
    end
  end
  
  def create
    @item = Item.new(params[:item])
    @item.created_by = current_user
    @item.save!
    redirect_to root_path
  end
  
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
    
end

app/views/items/_form.html.haml
= simple_form_for @item, :html => {:multipart => true, :class => 'form-horizontal'} do |f|
	.control-group
		%label.control-label Name
		.controls
			= f.input :name, :label => false
	.control-group
		%label.control-label Document
		.controls
			= f.input :file, :label => 'Document', :label => false, :as => :file
			- unless f.object.file.file.nil?
				%p= f.object.file_filename
	.control-group
		%label.control-label Description
		.controls
			= f.input :description, :as => :text, :label => false, :input_html => { :rows => '3' }
	.control-group
		%label.control-label Thumbnail
		.controls
			= f.input :preview, :label => 'Preview', :label => false, :as => :file
			- unless f.object.preview.file.nil?
				%img.img-polaroid(src="#{f.object.preview.url}" style="margin:0 10px 0 0;width:80px;height:80px")
	.control-group
		%label.control-label Tags
		.controls
			= f.input :tag_list, :label => false, :placeholder => 'Comma seperated'
	.control-group
		.controls
			%a.btn(href="/") Cancel
			%button.btn.btn-primary Save

app/views/items/_items_list.html.haml
- @items.each do |item|
	%tr
		%td.thumb
			%img.img-polaroid(src="#{item.preview.thumb.url}" style="margin:0 10px 0 0;width:100px;height:100px")
			%ul
				- unless item.file.file.nil?
					%li
						Size:
						= number_to_human_size(item.file.file.size)
					%li
						Added:
						= item.created_at.strftime("%m/%d/%Y")
				- unless item.user.blank?
					%li 
						By:
						= item.user.name
				%li
					= render :partial => '/items/like', :object => item
		%td
			%h4
				%a{:href=> item_path(item)}= item.name
			.download
				%span.icon-file
				%a(href="#{item.file.url}")
					= item.file_filename
			%p= item.description
			- unless item.tags.blank?
				%p.tags 
					Tags:
					= item.tags.map{|t| link_to(t, tag_path(t)) }.join(', ').html_safe

app/views/items/_like.html.haml
.rating
	= link_to('Like', like_item_path(like), :remote => true, :'data-type' => 'html', :class => 'rate')
	%span.badge{:id => "like_count_#{like._id}"}
		#{like.rating_count}

app/views/items/edit.html.haml
= render :partial => 'form'

app/views/items/index.html.haml
.row-fluid
	.span6.content
		- if tagged?
			.tagged-header
				%h4
					.prefix Documents tagged as:
					= params[:id].titlecase
					= link_to 'remove...', root_path, :class => 'remove'
		- if search?
			.tagged-header
				%h4
					.prefix Search results for as:
					= params[:query]
					= link_to 'remove...', root_path, :class => 'remove'
		- if flash
			- flash.each do |k,v|
				.alert.alert-block{ :class => "alert-#{k.to_s}" }= v
		= simple_form_for Item.new, :url => uploads_path, :html => { :enctype => "multipart/form-data", :id => 'fileupload' } do |f|
			.file-uploads-list.hide(role="presentation")
				.fileinput-button.hidden
					= f.input :file, :as => 'file', :label => false, :input_html => { :multiple => 'multiple', :id => 'active_uploader' }
				.files(data-toggle="modal-gallery" data-target="#modal-gallery")
				.upload-buttons.fileupload-buttonbar
					%input.toggle(type="hidden" value="1")
					%button.btn.btn-large.cancel(type="reset")
						Cancel
					%button.btn.btn-success.btn-large.start(type="submit")
						Upload documents
					
		%table.table.files
			%tbody.items-list
				= render '/items/items_list'
		.spinner
		
	.span3.sidebar
		.document-drop-area
			Drop documents here to upload
		%button#test_btn.btn.btn-primary.icon-plus(style="display:block;width:219px")
			Browse for documents...
		.search
			%h4 Search
			%form{:action => search_path, :method => 'get', :class => search? ? 'active-search' : ''}
				.input-append
					%input.span10.query{:type=>'text', :name => 'query', :value => params[:query], :style=>"position:relative;top:1px;height:31px!important;"}
					%button.btn.icon-search{:type=>'submit'}
				- if search?
					%a.icon-remove-sign{ :href => root_path }
		.tag-list
			%h4 Tags
			%ul
				- @tags.each do |tag|
					%li= link_to(tag.titlecase, tag_path(tag))
	.span3.activities
		%h4 Activities
		- @activities.each do |activity|
			.activity
				.row-fluid
					.span3
						%img.img-polaroid(src="#{activity.user.avatar.url}" style="width:50px;height:50px")
					.span9
						The document "#{link_to(activity.item.name, item_path(activity.item))}" was
						= activity.type.downcase
						by
						= mail_to(activity.user.email,activity.user.name)
						%br
						= l(activity.created_at, :format => :short)
				.row-fluid
					.span12
						%hr
= render '/uploads/js_templates'

app/views/items/new.html.haml
= simple_form_for @item, :html => {:multipart => true, :class => 'form-horizontal'} do |form|
	= render :partial => 'form', :object => form

app/views/items/show.html.haml
.row-fluid
	.span8.content
		%table.table.files
			%tbody
				%tr
					%td.preview
						%img.img-polaroid(src="#{@item.preview.thumb.url}" style="margin:0 10px 0 0;width:100px;height:100px")
						%ul
							- unless @item.file.file.nil?
								%li
									Size:
									= number_to_human_size(@item.file.file.size)
								%li
									Added:
									= @item.created_at.strftime("%m/%d/%Y")
							- unless @item.user.blank?
								%li 
									By:
									= @item.user.name
							%li
								= render :partial => 'like', :object => @item
					%td
						%h4
							= @item.name
						.download
							%span.icon-file
							%a(href="#{@item.file.url}")
								= @item.file_filename
						%p= @item.description
						- unless @item.tags.blank?
							%p.tags 
								Tags:
								= @item.tags.map{|t| link_to(t, tag_path(t)) }.join(', ').html_safe
						%p
							%a.btn{ :href => root_path } Close
							%a.btn.btn-primary{:href=> edit_item_path(@item)} Edit
						.comments{ :style => "display:#{@item.comments.blank? ? 'none' : 'static'}"}
							%hr
							%h5 Comments
							= render :partial => '/comments/comment', :collection => @item.comments
						%p(style="margin-top:30px")
							= simple_form_for @item.comments.build, :url => comments_path, :remote => true, :html => { :'data-type' => 'html' } do |f|
								= hidden_field_tag 'id', @item.id
								= f.input :body, :as => :text, :label => false, :placeholder => 'Write a comment', :input_html => { :rows => 3, :class => 'span12'}
								= f.submit 'Add comment', :class => 'btn'
							
						
	- unless @item.versions.reverse.blank?
		.span4.sidebar
			%h4 Versions
			- @item.versions.each do |version|
				.row-fluid
					.span3
						%img.img-polaroid(src="#{version.user.avatar.url}" style="width:50px;height:50px")
					.span9
						Last updated by
						= mail_to(version.user.email, version.user.name)
						on
						= l(version.updated_at, :format => :long)
						%br
						= link_to('View', item_version_path(@item, version.version))
						
				.row-fluid
					.span12
						%hr
	